# 数据库配置
db:
  host: localhost
  port: 3306
  user: upsdata
  password: 7FAZyEthEXhxNEPh
  dbname: upsdata

# 任务配置
task:
  tableName: users
  columns: ["platform_code","trading_time","payer_email","payer_country","consignee_country","consignee_phone","express_group_name","express_company_name"] # 数据列映射
  dataColumn: [1,21,49,51,65,72,137,142] # 数据列
  batchSize: 1000                   # 每批处理行数
  delimiter: ","                    # TXT文件分隔符（默认逗号）
  txtBeginLine: 1                   # TXT文件开始行数（默认1）
  csvBeginLine: 1                   # CSV文件开始行数（默认1）
  xlsxBeginLine: 1                   # XLSX文件开始行数（默认1）
  mulitipleTable: false             # 是否多表,如果多表就采用携程处理，同时插入多个表
  table:
    - tableName: shipedData
     