# 数据库配置
db:
  host: localhost
  port: 3306
  user: test
  password: 123456
  dbname: test

# 任务配置
task:
  tableName: users
  columns: ["name","phone","addr"] # 数据列映射
  dataColumn: [1,2,3] # 数据列
  batchSize: 1000                   # 每批处理行数
  delimiter: ","                    # TXT文件分隔符（默认逗号）
  txtBeginLine: 1                   # TXT文件开始行数（默认1）
  csvBeginLine: 1                   # CSV文件开始行数（默认1）
  xlsxBeginLine: 1                   # XLSX文件开始行数（默认1）
  mulitipleTable: false             # 是否多表,如果多表就采用携程处理，同时插入多个表
     